services:
  - type: web
    name: local-civic-issue
    env: node
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://lokeshroyal:Loki123@cluster0.mqkh2ng.mongodb.net/Lokesh
      - key: JWT_SECRET
        value: mysupersecretkey123
